-- Run this in SnowSQL as your admin user (RITWIKSHARAN)
-- snowsql -a UVWIABH-FC16241 -u RITWIKSHARAN
-- Then paste these 4 lines:

DROP USER IF EXISTS careintel_svc;

CREATE USER careintel_svc
  TYPE = SERVICE
  DEFAULT_ROLE = SYSADMIN
  DEFAULT_WAREHOUSE = COMPUTE_WH
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApkOfPfN7vp/+Dsx1vApe031fCnWS1s4CVI+U+nX7LIHoOghNubxNWKKY8D78KeIfFADG37YSThl+m42aKTPOtlA3Q5gZaAGgvFkVqjyaH1ycUW0qYgNmlChuUqTHUo0gLYfoaN47eDSEZPs1uzp/e0nyRHrHujFoiYxKdiBMU3nqRlTFADfSyM7I7ucp1pcRZ5j9f7l3aXD+fodnfVIhHeO2sWpO1gINKiMEzAKT1VAQqWKSL6OYISnVBvXMU3nhPXLJ0KjRw1kanuXJSbiGKXs4u6GfUVgKg54qtGUPHhe6i1a6tmZuPzcNoJZmcnn1XeIeMDJrYIBz8HVmYBuGOQIDAQAB';

GRANT ROLE SYSADMIN TO USER careintel_svc;

-- Verify it worked:
DESC USER careintel_svc;
